### PR TITLE
Update neb_make_pymatgen.py

### PR DESCRIPTION
**Pull request by Luc1anoo**
Added "forces" property to IS and FS images when making initial chain. Details can be found in the following link: #15

### CODE REVIEW

**Comment by QuantumMisaka** [comment]
@MoseyQAQ May you check ?

**Review by QuantumMisaka — APPROVED** [review]
It looks there are no problems

**Comment by QuantumMisaka** [comment]
I shall merge it in advance and if there are problem we can revert

**Comment by MoseyQAQ** [comment]
@QuantumMisaka  LGTM

**Pull request merged**
