### PR TITLE
Update the neb_make_pymatgen.py

### PR DESCRIPTION
**Pull request by MoseyQAQ**
I have updated the neb_make_pymatgen.py

Example:
```bash
python .\neb_make_pymatgen.py -i .\0\OUT.ABACUS\running_scf.log .\9\OUT.ABACUS\running_scf.log -n 8
````

### CODE REVIEW

**Comment by MoseyQAQ** [comment]
@QuantumMisaka Dear Developer, I have updated  the script to generate the initial neb chain file using Pymatgen  + ASE, and made some modifications to make the script more easy to read and use.

**Comment by QuantumMisaka** [comment]
@MoseyQAQ Sorry to notice your PR too late, I'll have a look in convenient time

**Comment by QuantumMisaka** [comment]
@MoseyQAQ Thanks for your PR!

Could you add some function like that in the existing `neb_make.py` which allows users to
1. set initial magnetic moment
2. set constraints (by certain direction and certain height)
Since the running*.log by ABACUS do not have these information

**Comment by MoseyQAQ** [comment]
@QuantumMisaka  OK, I will update the code. Thanks for your feedback!

**Comment by MoseyQAQ** [comment]
@QuantumMisaka The new functions have been added, please check.

**Comment by QuantumMisaka** [comment]
@MoseyQAQ Thanks a lot!

For dependencies, in my recollection the installation method for pymatgen is recommended to be `conda install -c conda-forge` ?

**Review by QuantumMisaka — APPROVED** [review]
LGTM

**Comment by MoseyQAQ** [comment]
> @MoseyQAQ Thanks a lot!
> 
> For dependencies, in my recollection the installation method for pymatgen is recommended to be `conda install -c conda-forge` ?

yes. More detailed information can be seen at: https://pymatgen.org/installation.html

**Comment by QuantumMisaka** [comment]
@MoseyQAQ Thanks! You're welcome to have my contact: QQ 948967102

**Pull request merged**
